import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main id="content">
        {/* <!-- =========={ HERO }==========  --> */}
        <div id="hero" className="section bg-gradient-primary py-8 py-lg-9 overflow-hidden">
          {/* <!-- background overlay --> */}
          <div className="overlay bg-gradient-primary opacity-90 z-index-n1"></div>

          {/* <!-- rocket moving up animation --> */}
          <div className="particle">
            <div className="particle-move-up d-none d-lg-block particle-move-up-1 text-light z-index-n1 opacity-60">
              🚀
            </div>
            <div className="particle-move-up particle-move-up-2 text-light z-index-n1 opacity-60">🚀</div>
            <div className="particle-move-up d-none d-sm-block particle-move-up-3 text-light z-index-n1 opacity-60">
              🚀
            </div>
            <div className="particle-move-up d-none d-xl-block particle-move-up-4 text-light z-index-n1 opacity-60">
              🚀
            </div>
            <div className="particle-move-up d-none d-sm-block particle-move-up-5 text-light z-index-n1 opacity-60">
              🚀
            </div>
            <div className="particle-move-up border-success text-light particle-move-up-6 z-index-n1 opacity-60">
              🚀
            </div>
            <div className="particle-move-up particle-move-up-7 z-index-n1 text-light opacity-60">🚀</div>
            <div className="particle-move-up particle-move-up-8 z-index-n1 text-light opacity-60">🚀</div>
            <div className="particle-move-up particle-move-up-9 z-index-n1 text-light opacity-60">🚀</div>
          </div>

          {/* <!-- scribble --> */}
          <figure
            className="scribble scale-4 opacity-10 top-50 start-0 z-index-n1"
            data-aos="fade-up-right"
            data-delay-aos="300"
          >
            🚀
          </figure>

          {/* <!-- scribble --> */}
          <figure
            className="scribble scale-5 opacity-10 top-50 start-0 z-index-n1"
            data-aos="fade-up-right"
            data-delay-aos="200"
          >
            <svg
              className="text-secondary"
              width="200"
              height="200"
              viewBox="0 0 200 200"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill="currentColor"
                d="M42.5,-66.2C57.1,-56.7,72.5,-48.4,81.1,-35.3C89.8,-22.2,91.8,-4.4,89.6,13C87.3,30.4,80.7,47.4,69.5,60.1C58.3,72.9,42.4,81.5,25.9,84.6C9.5,87.8,-7.4,85.4,-22.7,79.8C-37.9,74.1,-51.5,65.2,-60.9,53.3C-70.4,41.4,-75.8,26.6,-79,10.8C-82.1,-5,-83.1,-21.7,-77.7,-36.4C-72.4,-51,-60.7,-63.7,-46.7,-73.5C-32.7,-83.3,-16.4,-90.1,-1.2,-88.2C13.9,-86.3,27.8,-75.7,42.5,-66.2Z"
                transform="translate(100 100)"
              />
            </svg>
          </figure>

          {/* <!-- scribble --> */}
          <figure
            className="scribble scale-6 opacity-10 top-50 start-0 z-index-n1"
            data-aos="fade-up-right"
            data-delay-aos="100"
          >
            <svg
              className="text-secondary"
              width="200"
              height="200"
              viewBox="0 0 200 200"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill="currentColor"
                d="M42.5,-66.2C57.1,-56.7,72.5,-48.4,81.1,-35.3C89.8,-22.2,91.8,-4.4,89.6,13C87.3,30.4,80.7,47.4,69.5,60.1C58.3,72.9,42.4,81.5,25.9,84.6C9.5,87.8,-7.4,85.4,-22.7,79.8C-37.9,74.1,-51.5,65.2,-60.9,53.3C-70.4,41.4,-75.8,26.6,-79,10.8C-82.1,-5,-83.1,-21.7,-77.7,-36.4C-72.4,-51,-60.7,-63.7,-46.7,-73.5C-32.7,-83.3,-16.4,-90.1,-1.2,-88.2C13.9,-86.3,27.8,-75.7,42.5,-66.2Z"
                transform="translate(100 100)"
              />
            </svg>
          </figure>

          {/* <!-- scribble --> */}
          <figure className="scribble scale-7 opacity-10 top-50 start-0 z-index-n1" data-aos="fade-up-right">
            <svg
              className="text-secondary"
              width="200"
              height="200"
              viewBox="0 0 200 200"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill="currentColor"
                d="M42.5,-66.2C57.1,-56.7,72.5,-48.4,81.1,-35.3C89.8,-22.2,91.8,-4.4,89.6,13C87.3,30.4,80.7,47.4,69.5,60.1C58.3,72.9,42.4,81.5,25.9,84.6C9.5,87.8,-7.4,85.4,-22.7,79.8C-37.9,74.1,-51.5,65.2,-60.9,53.3C-70.4,41.4,-75.8,26.6,-79,10.8C-82.1,-5,-83.1,-21.7,-77.7,-36.4C-72.4,-51,-60.7,-63.7,-46.7,-73.5C-32.7,-83.3,-16.4,-90.1,-1.2,-88.2C13.9,-86.3,27.8,-75.7,42.5,-66.2Z"
                transform="translate(100 100)"
              />
            </svg>
          </figure>

          <div className="container">
            {/* <!-- row --> */}
            <div className="row justify-content-center">
              {/* <!-- hero content --> */}
              <div className="col-md-9 col-lg-6 align-self-center pe-lg-5" data-aos="flip-up">
                <div className="text-center text-lg-start mt-4 mt-lg-0">
                  <div className="mb-3">
                    <span className="badge bg-secondary rounded">New</span>
                    <span className="text-light ms-1">Next Generation Template</span>
                  </div>
                  <div className="mb-5">
                    <h1 className="display-5 fw-bold text-white mb-3">
                      <span className="text-warning">Core Web Vital</span>
                      <br />
                      Template for
                      <span
                        data-toggle="typed"
                        data-options='{"strings": ["StartUp", "Apps", "Company", "Portfolio"]}'
                      ></span>
                    </h1>
                    <p className="lead text-light">
                      Onekit is a Bootstrap 5 landing page template with a flat design and fast loading. This template
                      is perfect for building awesome landing page sites.
                    </p>
                  </div>
                  <a className="btn btn-white hover-button-up" href="#performance">
                    {/* <!-- <i className="fas fa-desktop"></i> --> */}
                    🚀 Test Drive
                  </a>
                </div>
              </div>

              {/* <!-- hero image --> */}
              <div className="col-md-9 col-lg-6 align-self-center">
                <div
                  className="px-3 px-sm-7 px-md-2 px-xl-7 mt-5 mt-lg-0 mb-n9"
                  data-aos="fade-up"
                  data-aos-delay="100"
                >
                  {/* <!--googleoff: index--> */}
                  <img className="img-fluid animated-up-down" src="/img-min/svg/start_up.svg" alt="images title" />

                  {/* <!--googleon: index--> */}
                </div>
              </div>
            </div>

            {/* <!-- end row --> */}
          </div>

          {/* <!-- waves start --> */}
        </div>
        {/* <!-- end hero --> */}
        {/* <!-- =========={ DEMO }==========  --> */}
        <div id="demo" className="section pb-4 pb-md-5 bg-light">
          <div className="container">
            <div className="position-relative">
              {/* <!-- scribble --> */}
              <figure className="scribble scale-2 d-none d-md-block top-0 end-0 me-lg-7 z-index-n1">🚀</figure>
            </div>
            {/* <!-- row --> */}
            <div className="row text-center">
              <div className="col-12">
                <div className="mb-5">
                  <h2 className="h3 fw-bold">Landing Pages</h2>
                  <hr className="divider my-4 mx-auto bg-warning border-warning" />
                  <p className="lead text-muted">Pre-build landing pages for your your personal and business site.</p>
                  <p className="lead text-muted">
                    All demo page are optimized with{' '}
                    <a href="#performance" className="fw-medium">
                      Google Core Web Vitals
                    </a>
                    .
                  </p>
                </div>
              </div>
              <div className="col-md-6 col-lg-4 px-sm-4" data-aos="fade-up">
                {/* <!-- demo card --> */}
                <div className="card border-0 mb-5 rounded-3 overflow-hidden shadow-sm hover-box-up">
                  <a href="index-default.html">
                    <img className="img-fluid w-100" src="/img-min/demo/img1.jpg" alt="Bootstrap 5 landing template" />
                  </a>
                  <div className="card-body">
                    <a href="index-default.html">
                      <h3 className="h5">Default</h3>
                    </a>
                  </div>
                </div>

                {/* <!-- end demo card --> */}
              </div>
              <div className="col-md-6 col-lg-4 px-sm-4" data-aos="fade-up" data-aos-delay="100">
                {/* <!-- demo card --> */}
                <div className="card border-0 mb-5 rounded-3 overflow-hidden shadow-sm hover-box-up">
                  <a href="index-apps.html">
                    <img className="img-fluid w-100" src="/img-min/demo/img2.jpg" alt="Landing page template" />
                  </a>
                  <div className="card-body">
                    <a href="index-apps.html">
                      <h3 className="h5">Mobile Apps</h3>
                    </a>
                  </div>
                </div>

                {/* <!-- end demo card --> */}
              </div>
              <div className="col-md-6 col-lg-4 px-sm-4" data-aos="fade-up" data-aos-delay="200">
                {/* <!-- demo card --> */}
                <div className="card border-0 mb-5 rounded-3 overflow-hidden shadow-sm hover-box-up">
                  <a href="index-agency.html">
                    <img className="img-fluid w-100" src="/img-min/demo/img8.jpg" alt="Bootstrap agency template" />
                  </a>
                  <div className="card-body">
                    <a href="index-agency.html">
                      <h3 className="h5">Agency</h3>
                    </a>
                  </div>
                </div>

                {/* <!-- end demo card --> */}
              </div>
              <div className="col-md-6 col-lg-4 px-sm-4" data-aos="fade-up">
                {/* <!-- demo card --> */}
                <div className="card border-0 mb-5 rounded-3 overflow-hidden shadow-sm hover-box-up">
                  <a href="index-portfolio.html">
                    <img className="img-fluid w-100" src="/img-min/demo/img4.jpg" alt="bootstrap portfolio template" />
                  </a>
                  <div className="card-body">
                    <a href="index-portfolio.html">
                      <h3 className="h5">Portfolio</h3>
                    </a>
                  </div>
                </div>

                {/* <!-- end demo card --> */}
              </div>
              <div className="col-md-6 col-lg-4 px-sm-4" data-aos="fade-up" data-aos-delay="100">
                {/* <!-- demo card --> */}
                <div className="card border-0 mb-5 rounded-3 overflow-hidden shadow-sm hover-box-up">
                  <a href="index-personal.html">
                    <img className="img-fluid w-100" src="/img-min/demo/img5.jpg" alt="Bootstrap personal template" />
                  </a>
                  <div className="card-body">
                    <a href="index-personal.html">
                      <h3 className="h5">Personal</h3>
                    </a>
                  </div>
                </div>

                {/* <!-- end demo card --> */}
              </div>
              <div className="col-md-6 col-lg-4 px-sm-4" data-aos="fade-up" data-aos-delay="200">
                {/* <!-- demo card --> */}
                <div className="card border-0 mb-5 rounded-3 overflow-hidden shadow-sm hover-box-up">
                  <a href="index-course.html">
                    <img
                      className="img-fluid w-100"
                      src="/img-min/demo/img6.jpg"
                      alt="Bootstrap online course template"
                    />
                  </a>
                  <div className="card-body">
                    <a href="index-course.html">
                      <h3 className="h5">Online Course</h3>
                    </a>
                  </div>
                </div>

                {/* <!-- end demo card --> */}
              </div>
              <div className="col-md-6 col-lg-4 px-sm-4" data-aos="fade-up">
                {/* <!-- demo card --> */}
                <div className="card border-0 mb-5 rounded-3 overflow-hidden shadow-sm hover-box-up">
                  <a href="index-coworking.html">
                    <img className="img-fluid w-100" src="/img-min/demo/img7.jpg" alt="Bootstrap coworking template" />
                  </a>
                  <div className="card-body">
                    <a href="index-coworking.html">
                      <h3 className="h5">Coworking</h3>
                    </a>
                  </div>
                </div>

                {/* <!-- end demo card --> */}
              </div>
              <div className="col-md-6 col-lg-4 px-sm-4" data-aos="fade-up" data-aos-delay="100">
                {/* <!-- demo card --> */}
                <div className="card border-0 mb-5 rounded-3 overflow-hidden shadow-sm hover-box-up">
                  <a href="index-company.html">
                    <img
                      className="img-fluid w-100"
                      src="/img-min/demo/img3.jpg"
                      alt="Bootstrap company profile template"
                    />
                  </a>
                  <div className="card-body">
                    <a href="index-company.html">
                      <h3 className="h5">Company Profile</h3>
                    </a>
                  </div>
                </div>

                {/* <!-- end demo card --> */}
              </div>
              <div className="col-md-6 col-lg-4 px-sm-4" data-aos="fade-up" data-aos-delay="200">
                {/* <!-- demo card --> */}
                <div className="card border-0 mb-5 rounded-3 overflow-hidden shadow-sm hover-box-up">
                  <a href="index-desktop.html">
                    <img
                      className="img-fluid w-100"
                      src="/img-min/demo/img9.jpg"
                      alt="Bootstrap desktop app template"
                    />
                  </a>
                  <div className="card-body">
                    <a href="index-desktop.html">
                      <h3 className="h5">Desktop Apps</h3>
                    </a>
                  </div>
                </div>

                {/* <!-- end demo card --> */}
              </div>
              ;
            </div>
            {/* <!-- end row --> */};
          </div>
          ;
        </div>
        {/* <!-- End demo --> */};{/* <!-- =========={ INTROCLUDING }==========  --> */}
        <div id="qr-code" className="section bg-gradient-primary">
          <div className="container-fluid p-0">
            <div className="row g-0">
              {/* <!-- img block --> */}
              <div
                className="col-lg-4 order-lg-2 text-white showcase-img"
                style={{ backgroundImage: "url('/img-min/section/overview1.jpg')" }}
              >
                <div className="lightgallery-thumbnail icon-center">
                  <a aria-label="Introcluding Onekit" href="https://www.youtube.com/watch?v=BGPSIUZdTkc">
                    <div className="position-relative text-white">
                      {/* <!-- <i className="fas fa-play-circle play-btn-icon" aria-hidden="true"></i> --> */}
                      🚀
                      <div className="play-btn-hover bg-primary opacity-80"></div>
                    </div>
                  </a>
                </div>
              </div>

              {/* <!-- content block --> */}
              <div className="col-lg-8 order-lg-1 my-auto showcase-text text-center text-md-start">
                <div className="position-relative overflow-hidden">
                  {/* <!-- scribble --> */}
                  <figure className="scribble scale-5 opacity-10 bottom-0 end-0 z-index-n1">
                    <svg
                      className="text-secondary"
                      width="200"
                      height="200"
                      viewBox="0 0 200 200"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill="currentColor"
                        d="M42.5,-66.2C57.1,-56.7,72.5,-48.4,81.1,-35.3C89.8,-22.2,91.8,-4.4,89.6,13C87.3,30.4,80.7,47.4,69.5,60.1C58.3,72.9,42.4,81.5,25.9,84.6C9.5,87.8,-7.4,85.4,-22.7,79.8C-37.9,74.1,-51.5,65.2,-60.9,53.3C-70.4,41.4,-75.8,26.6,-79,10.8C-82.1,-5,-83.1,-21.7,-77.7,-36.4C-72.4,-51,-60.7,-63.7,-46.7,-73.5C-32.7,-83.3,-16.4,-90.1,-1.2,-88.2C13.9,-86.3,27.8,-75.7,42.5,-66.2Z"
                        transform="translate(100 100)"
                      />
                    </svg>
                  </figure>

                  {/* <!-- scribble --> */}
                  <figure className="scribble scale-6 opacity-10 bottom-0 end-0 z-index-n1">
                    <svg
                      className="text-secondary"
                      width="200"
                      height="200"
                      viewBox="0 0 200 200"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill="currentColor"
                        d="M42.5,-66.2C57.1,-56.7,72.5,-48.4,81.1,-35.3C89.8,-22.2,91.8,-4.4,89.6,13C87.3,30.4,80.7,47.4,69.5,60.1C58.3,72.9,42.4,81.5,25.9,84.6C9.5,87.8,-7.4,85.4,-22.7,79.8C-37.9,74.1,-51.5,65.2,-60.9,53.3C-70.4,41.4,-75.8,26.6,-79,10.8C-82.1,-5,-83.1,-21.7,-77.7,-36.4C-72.4,-51,-60.7,-63.7,-46.7,-73.5C-32.7,-83.3,-16.4,-90.1,-1.2,-88.2C13.9,-86.3,27.8,-75.7,42.5,-66.2Z"
                        transform="translate(100 100)"
                      />
                    </svg>
                  </figure>

                  {/* <!-- scribble --> */}
                  <figure className="scribble scale-7 opacity-10 bottom-0 end-0 z-index-n1">
                    <svg
                      className="text-secondary"
                      width="200"
                      height="200"
                      viewBox="0 0 200 200"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill="currentColor"
                        d="M42.5,-66.2C57.1,-56.7,72.5,-48.4,81.1,-35.3C89.8,-22.2,91.8,-4.4,89.6,13C87.3,30.4,80.7,47.4,69.5,60.1C58.3,72.9,42.4,81.5,25.9,84.6C9.5,87.8,-7.4,85.4,-22.7,79.8C-37.9,74.1,-51.5,65.2,-60.9,53.3C-70.4,41.4,-75.8,26.6,-79,10.8C-82.1,-5,-83.1,-21.7,-77.7,-36.4C-72.4,-51,-60.7,-63.7,-46.7,-73.5C-32.7,-83.3,-16.4,-90.1,-1.2,-88.2C13.9,-86.3,27.8,-75.7,42.5,-66.2Z"
                        transform="translate(100 100)"
                      />
                    </svg>
                  </figure>

                  {/* <!-- scribble --> */}
                  <figure className="scribble scale-8 opacity-10 bottom-0 end-0 z-index-n1">
                    <svg
                      className="text-secondary"
                      width="200"
                      height="200"
                      viewBox="0 0 200 200"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill="currentColor"
                        d="M42.5,-66.2C57.1,-56.7,72.5,-48.4,81.1,-35.3C89.8,-22.2,91.8,-4.4,89.6,13C87.3,30.4,80.7,47.4,69.5,60.1C58.3,72.9,42.4,81.5,25.9,84.6C9.5,87.8,-7.4,85.4,-22.7,79.8C-37.9,74.1,-51.5,65.2,-60.9,53.3C-70.4,41.4,-75.8,26.6,-79,10.8C-82.1,-5,-83.1,-21.7,-77.7,-36.4C-72.4,-51,-60.7,-63.7,-46.7,-73.5C-32.7,-83.3,-16.4,-90.1,-1.2,-88.2C13.9,-86.3,27.8,-75.7,42.5,-66.2Z"
                        transform="translate(100 100)"
                      />
                    </svg>
                  </figure>

                  <div className="px-4 px-lg-6 mt-5 mt-lg-7">
                    {/* <!-- Row --> */}
                    <div className="row justify-content-center">
                      <div
                        className="col-11 col-sm-8 col-lg-12 col-xl-6 order-xl-2 text-center text-md-start"
                        data-aos="flip-up"
                      >
                        <h3 className="fw-bold text-white mb-4">Try a live demo from your smartphone</h3>
                        <p className="text-light">
                          If you open this demo from laptop, please scan the QR code on this page to continue demo from
                          your smartphone.
                        </p>
                        <p className="text-light mb-5 mb-xl-4">
                          Don&#39;t forget to test PWA ( Progressive Web App ) feature by clicking &quotAdd to Home
                          Screen&quot.
                        </p>
                        <div className="d-none d-xl-block w-50 mx-auto">
                          <svg
                            className="text-warning"
                            width="126"
                            height="63"
                            viewBox="0 0 253.000000 125.000000"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <g
                              transform="translate(0.000000,125.000000) scale(0.100000,-0.100000)"
                              fill="currentColor"
                              stroke="none"
                            >
                              <path
                                d="M1719 1153 c-24 -21 -46 -41 -49 -44 -13 -18 -139 -79 -152 -74 -8 3
												  -21 18 -30 33 -27 45 -55 65 -80 58 -13 -3 -54 -33 -93 -66 -91 -79 -104 -81
												  -162 -36 -77 60 -131 46 -256 -62 -27 -23 -52 -42 -56 -42 -4 0 -13 16 -20 35
												  -32 90 -117 81 -288 -33 -29 -19 -55 -33 -56 -31 -2 2 -15 23 -30 47 -30 46
												  -30 46 -57 32 -24 -13 -200 -228 -200 -243 1 -7 9 -22 19 -34 28 -34 72 -21
												  135 40 l51 49 32 -37 c29 -33 36 -37 66 -31 18 3 49 17 67 31 19 14 38 25 44
												  25 6 0 24 13 41 28 16 15 47 35 67 45 35 15 37 15 43 -1 3 -10 23 -35 44 -56
												  57 -56 79 -52 159 27 37 36 85 74 107 85 l40 20 27 -21 c58 -48 73 -57 88 -53
												  8 2 31 7 50 10 23 4 55 24 95 61 33 30 65 55 71 55 6 0 17 -11 24 -25 7 -14
												  26 -33 42 -43 24 -15 35 -17 73 -8 30 7 44 15 42 25 -1 9 8 14 26 15 16 1 31
												  6 35 11 4 6 15 15 25 20 10 6 18 15 18 20 0 38 83 73 95 40 3 -8 14 -17 25
												  -20 11 -4 17 -10 14 -15 -3 -5 6 -12 20 -16 28 -7 54 16 54 46 1 20 -29 55
												  -52 64 -11 3 -21 15 -24 27 -3 11 -17 25 -32 30 -19 8 -22 12 -12 18 8 5 10
												  14 7 20 -14 21 -53 11 -97 -26z"
                              />
                              <path
                                d="M1930 880 c-25 -9 -97 -41 -160 -70 -133 -61 -213 -90 -248 -90 -13
												  0 -40 9 -58 21 -42 26 -67 21 -187 -32 -49 -22 -110 -45 -137 -51 -44 -10 -51
												  -9 -75 11 -15 11 -35 21 -44 21 -9 0 -65 -18 -125 -40 -61 -22 -118 -40 -127
												  -40 -10 0 -27 13 -39 30 -12 17 -30 30 -42 30 -27 0 -150 -84 -193 -132 -65
												  -72 -101 -76 -130 -15 -25 53 -59 62 -76 20 -7 -15 -25 -56 -40 -90 -34 -73
												  -34 -71 -9 -103 l20 -25 34 40 c32 37 35 39 52 24 11 -9 38 -25 60 -37 l42
												  -20 53 35 c30 19 55 39 57 43 11 30 116 110 144 110 9 0 18 -7 22 -15 3 -8 16
												  -15 30 -15 14 0 28 -5 31 -11 10 -15 57 -3 159 42 l88 39 29 -25 c34 -28 101
												  -45 107 -26 2 6 9 11 16 11 6 0 45 16 86 36 41 20 98 42 126 49 47 12 52 11
												  80 -11 50 -41 179 -24 223 29 7 10 19 17 26 17 7 0 55 28 107 63 52 34 113 71
												  136 81 47 21 58 42 41 79 -16 35 -27 38 -79 17z"
                              />
                              <path
                                d="M2205 519 c-139 -59 -359 -129 -430 -136 -59 -5 -66 -4 -95 21 -50
												  42 -83 36 -236 -44 l-135 -71 -32 27 c-41 35 -78 29 -205 -30 -54 -25 -108
												  -46 -120 -46 -20 0 -22 5 -22 51 0 57 -25 109 -51 109 -20 0 -63 -55 -55 -69
												  3 -5 -1 -11 -9 -15 -8 -3 -15 -17 -15 -30 0 -14 -7 -29 -16 -34 -13 -7 -14
												  -13 -4 -31 6 -13 9 -30 6 -38 -6 -16 19 -53 36 -53 4 0 8 11 8 24 0 36 10 56
												  29 55 10 0 11 -2 4 -6 -18 -7 -16 -32 2 -39 8 -4 12 -10 9 -15 -3 -5 1 -9 8
												  -9 7 0 18 -10 23 -23 8 -18 19 -23 58 -25 31 -2 55 2 69 12 12 9 29 16 36 16
												  8 0 27 11 44 25 41 35 101 51 133 37 14 -6 25 -18 25 -26 0 -14 15 -15 84 -7
												  4 1 6 8 2 16 -6 16 19 22 28 6 7 -10 56 -2 56 9 0 5 9 12 20 15 11 3 20 10 20
												  16 0 17 33 47 46 42 8 -3 29 5 48 16 33 21 35 21 65 4 17 -10 33 -25 36 -33 7
												  -20 76 -54 84 -41 4 5 27 9 51 8 25 -1 45 2 45 6 0 5 36 20 80 35 44 14 157
												  65 250 112 l170 85 1 43 c1 23 -2 42 -7 42 -5 0 -9 7 -9 15 0 23 -36 16 -135
												  -26z"
                              />
                            </g>
                          </svg>
                        </div>
                      </div>

                      <div className="col-11 col-sm-8 col-lg-6 order-xl-1 align-self-end" data-aos="fade-right">
                        <div className="px-xl-5 text-center">
                          <img className="img-fluid" src="/img-min/app/qr-demo.png" alt="demo qr code" />
                        </div>
                      </div>
                    </div>

                    {/* <!-- End Row --> */}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        ;{/* <!-- end Introcluding --> */}
        {/* <!-- =========={ FEATURES }==========  --> */}
        <div id="features" className="section pt-6 pt-md-7 pb-4 pb-md-5 bg-light">
          <div className="container">
            {/* <!-- row --> */}
            <div className="row text-center">
              <div className="col-12">
                <div className="mb-5">
                  <h2 className="h3 fw-bold">Core Features</h2>
                  <hr className="divider my-4 mx-auto bg-warning border-warning" />
                  <p className="lead text-muted">Modern features that will make your project easier.</p>
                </div>
              </div>

              <div className="col-md-6 col-lg-4 px-4 px-md-3" data-aos="fade-up">
                {/* <!-- service block --> */}
                <div className="p-4 mb-5 rounded-3 bg-white shadow-sm hover-box-up">
                  <div className="text-primary mb-3">
                    {/* <!-- icon --> */}
                    {/* <!-- <i className="fab fa-bootstrap"></i> --> */}
                    🚀
                  </div>
                  <h3 className="h5">Latest Bootstrap 5</h3>
                  <p>Supported latest Bootstrap 5, most popular front-end component library.</p>
                </div>

                {/* <!-- end service block --> */}
              </div>

              <div className="col-md-6 col-lg-4 px-4 px-md-3" data-aos="fade-up" data-aos-delay="100">
                {/* <!-- service block --> */}
                <div className="p-4 mb-5 rounded-3 bg-white shadow-sm hover-box-up">
                  <div className="text-primary mb-3">
                    {/* <!-- icon --> */}
                    {/* <!-- <i className="fab fa-"></i> --> */}
                    🚀
                  </div>
                  <h3 className="h5">Google Web Vitals</h3>
                  <p>Optimized by core web vital features from Google Web.Dev.</p>
                </div>

                {/* <!-- end service block --> */}
              </div>

              <div className="col-md-6 col-lg-4 px-4 px-md-3" data-aos="fade-up" data-aos-delay="200">
                {/* <!-- service block --> */}
                <div className="p-4 mb-5 rounded-3 bg-white shadow-sm hover-box-up">
                  <div className="text-primary mb-3">
                    {/* <!-- icon --> */}
                    {/* <!-- <i className="fab fa-npm"></i> --> */}
                    🚀
                  </div>
                  <h3 className="h5">Vanilla Javascript</h3>
                  <p>Template and major plugins using pure vanilla javascript.</p>
                </div>

                {/* <!-- end service block --> */}
              </div>

              <div className="col-md-6 col-lg-4 px-4 px-md-3" data-aos="fade-up">
                {/* <!-- service block --> */}
                <div className="p-4 mb-5 rounded-3 bg-white shadow-sm hover-box-up">
                  <div className="text-primary mb-3">
                    {/* <!-- icon --> */}

                    {/* <!-- <i className="fab fa-bootstrap"></i> --> */}
                    <svg
                      width="3rem"
                      height="3rem"
                      viewBox="0 0 16 16"
                      fill="currentColor"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M0 6a6 6 0 1112 0A6 6 0 010 6z"></path>
                      <path d="M12.93 5h1.57a.5.5 0 01.5.5v9a.5.5 0 01-.5.5h-9a.5.5 0 01-.5-.5v-1.57a6.953 6.953 0 01-1-.22v1.79A1.5 1.5 0 005.5 16h9a1.5 1.5 0 001.5-1.5v-9A1.5 1.5 0 0014.5 4h-1.79c.097.324.17.658.22 1z"></path>
                    </svg>
                  </div>
                  <h3 className="h5">Pure Svg Icons</h3>
                  <p>In default, we use pure svg icon. This is the icon for the modern web.</p>
                </div>

                {/* <!-- end service block --> */}
              </div>

              <div className="col-md-6 col-lg-4 px-4 px-md-3" data-aos="fade-up" data-aos-delay="100">
                {/* <!-- service block --> */}
                <div className="p-4 mb-5 rounded-3 bg-white shadow-sm hover-box-up">
                  <div className="text-primary mb-3">
                    {/* <!-- icon --> */}
                    {/* <!-- <i className="fab fa-"></i> --> */}
                    🚀
                  </div>
                  <h3 className="h5">Webp Images</h3>
                  <p>All png and jpg asset images are compressed to webp format.</p>
                </div>

                {/* <!-- end service block --> */}
              </div>

              <div className="col-md-6 col-lg-4 px-4 px-md-3" data-aos="fade-up" data-aos-delay="200">
                {/* <!-- service block --> */}
                <div className="p-4 mb-5 rounded-3 bg-white shadow-sm hover-box-up">
                  <div className="text-primary mb-3">
                    {/* <!-- icon --> */}
                    {/* <!-- <i className="fab fa-html5"></i> --> */}
                    🚀
                  </div>
                  <h3 className="h5">Premium plugins</h3>
                  <p>Included premium plugins Lightgallery, Isotope and Flickity.</p>
                </div>

                {/* <!-- end service block --> */}
              </div>

              <div className="col-md-6 col-lg-4 px-4 px-md-3" data-aos="fade-up">
                {/* <!-- service block --> */}
                <div className="p-4 mb-5 rounded-3 bg-white shadow-sm hover-box-up">
                  <div className="text-primary mb-3">
                    {/* <!-- icon --> */}
                    {/* <!-- <i className="fab fa-html5"></i> --> */}
                    🚀
                  </div>
                  <h3 className="h5">NPM Software</h3>
                  <p>Enjoy with the public registry tools you already love to use.</p>
                </div>

                {/* <!-- end service block --> */}
              </div>

              <div className="col-md-6 col-lg-4 px-4 px-md-3" data-aos="fade-up" data-aos-delay="100">
                {/* <!-- service block --> */}
                <div className="p-4 mb-5 rounded-3 bg-white shadow-sm hover-box-up">
                  <div className="text-primary mb-3">
                    {/* <!-- icon --> */}
                    {/* <!-- <i className="fab fa-gulp"></i> --> */}
                    🚀
                  </div>
                  <h3 className="h5">Built with Gulp</h3>
                  <p>Gulp making your project automatic and easy to running.</p>
                </div>

                {/* <!-- end service block --> */}
              </div>

              <div className="col-md-6 col-lg-4 px-4 px-md-3" data-aos="fade-up" data-aos-delay="200">
                {/* <!-- service block --> */}
                <div className="p-4 mb-5 rounded-3 bg-white shadow-sm hover-box-up">
                  <div className="text-primary mb-3">
                    {/* <!-- icon --> */}
                    {/* <!-- <i className="fab fa-sass"></i> --> */}
                    🚀
                  </div>
                  <h3 className="h5">Built with Sass</h3>
                  <p>Change one variable from scss and the theme adapts.</p>
                </div>

                {/* <!-- end service block --> */}
              </div>
            </div>

            {/* <!-- end row --> */}
          </div>
          ;
        </div>
        {/* <!-- End features --> */};{/* <!-- =========={ PERFORMANCE }==========  --> */}
        <div id="performance" className="section py-6 py-md-7 bg-white">
          <div className="container">
            {/* <!-- row --> */}
            <div className="row text-center">
              <div className="col-12">
                <div className="mb-5">
                  <h2 className="h3 fw-bold">Onekit Test Drive</h2>
                  <hr className="divider my-4 mx-auto bg-warning border-warning" />
                  <p className="lead text-muted">You should try onekit performance and features.</p>
                </div>
              </div>
            </div>

            {/* <!-- showcase 1 --> */}
            <div className="row mb-5 mb-lg-7">
              <div className="col-lg-6 align-self-center">
                <div className="px-5 px-md-7 mb-5 mb-lg-0" data-aos="fade-right" data-aos-delay="100">
                  <img src="/img-min/svg/rocket_boy.svg" className="img-fluid" alt="landing page" />
                </div>
              </div>
              <div className="col-lg-6">
                {/* <!-- processs vertical --> */}
                <ol className="process-vertical ps-0" data-aos="flip-up">
                  <li className="process-vertical-item">
                    <div className="process-vertical-icon">
                      <div className="process-vertical-icon-bg me-auto rounded-circle p-2">
                        <span>🚀</span>
                      </div>
                    </div>

                    <div className="process-vertical-content ms-lg-4">
                      <h3 className="h5">Google Core Web Vitals</h3>
                      <p>
                        Test the performance of Onekit template with Google Core Web Vitals in Web.Dev
                        <a
                          data-bs-toggle="tooltip"
                          data-bs-placement="top"
                          title="Click to test performance"
                          target="_blank"
                          rel="noopener noreferrer"
                          href="https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fonekit.madethemes.com%2F"
                        >
                          clik here
                        </a>
                        .
                      </p>
                    </div>
                  </li>

                  <li className="process-vertical-item">
                    <div className="process-vertical-icon">
                      <div className="process-vertical-icon-bg me-auto rounded-circle p-2">
                        <span>🚀</span>
                      </div>
                    </div>

                    <div className="process-vertical-content ms-lg-4">
                      <h3 className="h5">Fast Loading Time</h3>
                      <p>
                        Test the loading speed of Onekit template with Google Pagespeed Insights
                        <a
                          data-bs-toggle="tooltip"
                          data-bs-placement="top"
                          title="Click to test loading speed"
                          target="_blank"
                          rel="noopener noreferrer"
                          href="https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fonekit.madethemes.com"
                        >
                          clik here
                        </a>
                        .
                      </p>
                    </div>
                  </li>

                  <li className="process-vertical-item">
                    <div className="process-vertical-icon">
                      <div className="process-vertical-icon-bg me-auto rounded-circle p-2">
                        <span>
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className="text-primary"
                            width="1.5rem"
                            height="1.5rem"
                            fill="currentColor"
                            viewBox="0 0 512 512"
                          >
                            <path d="M330.7,352l77.72-192H356.9L303.74,284.07,265.93,160H226.32L185.74,284.07l-28.63-56.53L131.21,307l26.3,45h50.7l36.68-111.27,35,111.27Z" />
                            <path d="M48.79,286.09H80.44a93.39,93.39,0,0,0,25.62-3.21l8.18-25.19,22.88-70.39a55.75,55.75,0,0,0-6-7.82Q113.54,160,79.59,160H0V352H48.79Zm41.9-81.92q6.89,6.92,6.88,18.52t-6,18.53q-6.64,7.62-24.44,7.61H48.79V197.25H67.21q16.59,0,23.48,6.92ZM376.85,317.61l14.79-37.25h42.69l-20.26-56.51L439.41,160,512,352H458.47l-12.4-34.39Z" />
                          </svg>
                        </span>
                      </div>
                    </div>

                    <div className="process-vertical-content ms-lg-4">
                      <h3 className="h5">Progressive Web App</h3>
                      <p>
                        Scan
                        <a
                          data-bs-toggle="tooltip"
                          data-bs-placement="top"
                          title="Click to scan qr code"
                          href="#qr-code"
                        >
                          qr code
                        </a>
                        with your smartphone and open link. Click Add to Home Screen and site will installed like App.
                      </p>
                    </div>
                  </li>
                </ol>

                {/* <!-- end processs vertical --> */}
              </div>
            </div>

            {/* <!-- showcase 2 --> */}
            <div className="row mb-5 mb-lg-7">
              <div className="col-lg-6 order-lg-2 align-self-center">
                <div className="px-5 px-md-7 mb-5 my-lg-0" data-aos="fade-left" data-aos-delay="100">
                  <img src="/img-min/svg/coding.svg" className="img-fluid" alt="landing page" />
                </div>
              </div>

              <div className="col-lg-6 order-lg-1">
                {/* <!-- processs vertical --> */}
                <ol className="process-vertical ps-0" data-aos="flip-up">
                  <li className="process-vertical-item">
                    <div className="process-vertical-icon">
                      <div className="process-vertical-icon-bg me-auto rounded-circle p-2">
                        <span>
                          <svg
                            className="bi bi-bootstrap text-primary"
                            width="1.5rem"
                            height="1.5rem"
                            viewBox="0 0 16 16"
                            fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              fillRule="evenodd"
                              d="M12 1H4a3 3 0 00-3 3v8a3 3 0 003 3h8a3 3 0 003-3V4a3 3 0 00-3-3zM4 0a4 4 0 00-4 4v8a4 4 0 004 4h8a4 4 0 004-4V4a4 4 0 00-4-4H4z"
                              clipRule="evenodd"
                            ></path>
                            <path
                              fillRule="evenodd"
                              d="M8.537 12H5.062V3.545h3.399c1.587 0 2.543.809 2.543 2.11 0 .884-.65 1.675-1.483 1.816v.1c1.143.117 1.904.931 1.904 2.033 0 1.488-1.084 2.396-2.888 2.396zM6.375 4.658v2.467h1.558c1.16 0 1.764-.428 1.764-1.23 0-.78-.569-1.237-1.541-1.237H6.375zm1.898 6.229H6.375V8.162h1.822c1.236 0 1.887.463 1.887 1.348 0 .896-.627 1.377-1.811 1.377z"
                              clipRule="evenodd"
                            ></path>
                          </svg>
                        </span>
                      </div>
                    </div>

                    <div className="process-vertical-content ms-lg-4">
                      <h3 className="h5">Bootstrap 5</h3>
                      <p>Onekit supported Bootstrap 5 with pure vanilla javascript and no Jquery dependency</p>
                    </div>
                  </li>

                  <li className="process-vertical-item">
                    <div className="process-vertical-icon">
                      <div className="process-vertical-icon-bg me-auto rounded-circle p-2">
                        <span>
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            className="text-primary"
                            width="2rem"
                            height="2rem"
                            viewBox="5.006 23.881 199.987 95.238"
                          >
                            <title>W3C Logo</title>
                            <desc>
                              W3C is a trademark (registered in numerous countries) of the World Wide Web Consortium;
                              marks of W3C are registered and held by its host institutions MIT, ERCIM, and Keio. For
                              more information see: http://www.w3.org/
                            </desc>
                            <path
                              d="M52.352 24.412l16.955 57.643L86.26 24.412h45.965v5.73l-17.308 29.816c6.08 1.949 10.679 5.498 13.795 10.641 3.119 5.146 4.681 11.184 4.681 18.121 0 8.578-2.283 15.787-6.845 21.632-4.562 5.844-10.465 8.768-17.713 8.768-5.458 0-10.211-1.732-14.262-5.201-4.054-3.469-7.054-8.164-9.002-14.09l9.585-3.975c1.404 3.586 3.256 6.412 5.556 8.475 2.299 2.066 5.009 3.1 8.125 3.1 3.271 0 6.041-1.832 8.302-5.494 2.262-3.664 3.393-8.065 3.393-13.215 0-5.691-1.209-10.096-3.623-13.213-2.811-3.662-7.215-5.496-13.216-5.496h-4.674V64.4l16.367-28.297H95.63l-1.124 1.914-24.031 81.087h-1.169l-17.54-58.69-17.536 58.69h-1.168L5.006 24.408h12.276l16.953 57.643 11.46-38.815-5.611-18.826h12.273v-.004l-.005.006z"
                              fill="currentColor"
                            ></path>
                            <path
                              fill="currentColor"
                              d="M196.02 24.412c-2.41 0-4.574.869-6.215 2.535-1.74 1.768-2.709 4.051-2.709 6.412s.922 4.549 2.611 6.266c1.717 1.74 3.928 2.686 6.314 2.686 2.334 0 4.6-.945 6.36-2.658 1.688-1.641 2.611-3.828 2.611-6.289a8.944 8.944 0 0 0-2.584-6.289c-1.7-1.745-3.94-2.663-6.38-2.663h-.008zm7.78 9.024c0 2.064-.799 3.979-2.26 5.393-1.543 1.494-3.457 2.289-5.569 2.289-1.986 0-3.949-.818-5.418-2.311-1.466-1.494-2.287-3.406-2.287-5.443 0-2.039.846-4.027 2.36-5.566 1.416-1.443 3.328-2.211 5.416-2.211 2.14 0 4.051.799 5.543 2.311 1.45 1.438 2.22 3.373 2.22 5.538h-.005zm-7.53-5.321h-3.826v10.143h1.914v-4.324h1.892l2.063 4.324h2.137l-2.264-4.621c1.465-.301 2.312-1.293 2.312-2.734.01-1.84-1.391-2.788-4.221-2.788h-.007zm-.35 1.244c1.789 0 2.609.498 2.609 1.74 0 1.191-.82 1.617-2.563 1.617h-1.616v-3.357h1.57zM180.971 23.881l1.987 12.09-7.039 13.469s-2.701-5.715-7.19-8.875c-3.781-2.664-6.246-3.244-10.101-2.449-4.948 1.021-10.562 6.938-13.01 14.234-2.931 8.727-2.959 12.953-3.063 16.832-.164 6.223.816 9.896.816 9.896s-4.275-7.906-4.234-19.486c.027-8.268 1.328-15.764 5.152-23.16 3.365-6.504 8.367-10.408 12.807-10.867 4.59-.473 8.215 1.738 11.021 4.131 2.94 2.516 5.916 8.01 5.916 8.01l6.92-13.825h.018zM181.84 92.289s-3.111 5.562-5.049 7.705c-1.939 2.145-5.408 5.918-9.691 7.807-4.283 1.887-6.529 2.24-10.764 1.836-4.229-.406-8.16-2.854-9.537-3.877-1.377-1.021-4.898-4.029-6.889-6.836-1.992-2.807-5.102-8.416-5.102-8.416s1.731 5.623 2.819 8.01c.623 1.375 2.541 5.576 5.267 9.232 2.541 3.41 7.475 9.283 14.973 10.609 7.498 1.328 12.65-2.041 13.926-2.855 1.273-.814 3.961-3.066 5.664-4.889 1.775-1.896 3.457-4.32 4.385-5.773.682-1.062 1.789-3.215 1.789-3.215l-1.79-9.331-.001-.007z"
                            ></path>
                          </svg>
                        </span>
                      </div>
                    </div>

                    <div className="process-vertical-content ms-lg-4">
                      <h3 className="h5">Validated by W3C</h3>
                      <p>
                        All HTML pages are validated by W3C standards, test Onekit quality code
                        <a
                          data-bs-toggle="tooltip"
                          data-bs-placement="top"
                          title="Click to test quality code"
                          target="_blank"
                          rel="noopener noreferrer"
                          href="https://validator.w3.org/nu/?doc=https%3A%2F%2Fonekit.madethemes.com%2F"
                        >
                          clik here
                        </a>
                        .
                      </p>
                    </div>
                  </li>

                  <li className="process-vertical-item">
                    <div className="process-vertical-icon">
                      <div className="process-vertical-icon-bg me-auto rounded-circle p-2">
                        <span>🚀</span>
                      </div>
                    </div>

                    <div className="process-vertical-content ms-lg-4">
                      <h3 className="h5">RTL Supported</h3>
                      <p>
                        Supported RTL layout for Arabic, Persian, Urdu and etc. Test RTL layout
                        <Link href="index-rtl.html">
                          <a data-bs-toggle="tooltip" data-bs-placement="top" title="Click to test demo rtl">
                            clik here
                          </a>
                        </Link>
                      </p>
                    </div>
                  </li>
                </ol>

                {/* <!-- end processs vertical --> */}
              </div>
            </div>

            {/* <!-- showcase 3 --> */}
            <div className="row">
              <div className="col-lg-6 align-self-center">
                <div className="px-5 px-md-7 mb-5 my-lg-0" data-aos="fade-right" data-aos-delay="100">
                  <img src="/img-min/svg/wallet.svg" className="img-fluid" alt="landing page" />
                </div>
              </div>
              <div className="col-lg-6">
                {/* <!-- processs vertical --> */}
                <ol className="process-vertical ps-0" data-aos="flip-up">
                  <li className="process-vertical-item">
                    <div className="process-vertical-icon">
                      <div className="process-vertical-icon-bg me-auto rounded-circle p-2">
                        <span>
                          <svg
                            className="bi bi-arrows-fullscreen text-primary"
                            width="1.5rem"
                            height="1.5rem"
                            viewBox="0 0 16 16"
                            fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              fillRule="evenodd"
                              d="M1.464 10.536a.5.5 0 01.5.5v3h3a.5.5 0 010 1h-3.5a.5.5 0 01-.5-.5v-3.5a.5.5 0 01.5-.5z"
                              clipRule="evenodd"
                            ></path>
                            <path
                              fillRule="evenodd"
                              d="M5.964 10a.5.5 0 010 .707l-4.146 4.147a.5.5 0 01-.707-.708L5.257 10a.5.5 0 01.707 0zm8.854-8.854a.5.5 0 010 .708L10.672 6a.5.5 0 01-.708-.707l4.147-4.147a.5.5 0 01.707 0z"
                              clipRule="evenodd"
                            ></path>
                            <path
                              fillRule="evenodd"
                              d="M10.5 1.5A.5.5 0 0111 1h3.5a.5.5 0 01.5.5V5a.5.5 0 01-1 0V2h-3a.5.5 0 01-.5-.5zm4 9a.5.5 0 00-.5.5v3h-3a.5.5 0 000 1h3.5a.5.5 0 00.5-.5V11a.5.5 0 00-.5-.5z"
                              clipRule="evenodd"
                            ></path>
                            <path
                              fillRule="evenodd"
                              d="M10 9.964a.5.5 0 000 .708l4.146 4.146a.5.5 0 00.708-.707l-4.147-4.147a.5.5 0 00-.707 0zM1.182 1.146a.5.5 0 000 .708L5.328 6a.5.5 0 00.708-.707L1.889 1.146a.5.5 0 00-.707 0z"
                              clipRule="evenodd"
                            ></path>
                            <path
                              fillRule="evenodd"
                              d="M5.5 1.5A.5.5 0 005 1H1.5a.5.5 0 00-.5.5V5a.5.5 0 001 0V2h3a.5.5 0 00.5-.5z"
                              clipRule="evenodd"
                            ></path>
                          </svg>
                        </span>
                      </div>
                    </div>

                    <div className="process-vertical-content ms-lg-4">
                      <h3 className="h5">Lightgallery Js</h3>
                      <p>Included Premium plugin Lightgallery.Js javascript lightbox gallery.</p>
                    </div>
                  </li>

                  <li className="process-vertical-item">
                    <div className="process-vertical-icon">
                      <div className="process-vertical-icon-bg me-auto rounded-circle p-2">
                        <span>
                          <svg
                            className="bi bi-image text-primary"
                            width="1.5rem"
                            height="1.5rem"
                            viewBox="0 0 16 16"
                            fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              fillRule="evenodd"
                              d="M14.002 2h-12a1 1 0 00-1 1v10a1 1 0 001 1h12a1 1 0 001-1V3a1 1 0 00-1-1zm-12-1a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V3a2 2 0 00-2-2h-12z"
                              clipRule="evenodd"
                            ></path>
                            <path d="M10.648 7.646a.5.5 0 01.577-.093L15.002 9.5V14h-14v-2l2.646-2.354a.5.5 0 01.63-.062l2.66 1.773 3.71-3.71z"></path>
                            <path
                              fillRule="evenodd"
                              d="M4.502 7a1.5 1.5 0 100-3 1.5 1.5 0 000 3z"
                              clipRule="evenodd"
                            ></path>
                          </svg>
                        </span>
                      </div>
                    </div>

                    <div className="process-vertical-content ms-lg-4">
                      <h3 className="h5">Flickity Carousel</h3>
                      <p>Included Premium plugin Flickity touch, responsive, flickable carousels.</p>
                    </div>
                  </li>

                  <li className="process-vertical-item">
                    <div className="process-vertical-icon">
                      <div className="process-vertical-icon-bg me-auto rounded-circle p-2">
                        <span>
                          <svg
                            className="bi bi-filter text-primary"
                            width="1.5rem"
                            height="1.5rem"
                            viewBox="0 0 16 16"
                            fill="currentColor"
                            xmlns="http://www.w3.org/2000/svg"
                          >
                            <path
                              fillRule="evenodd"
                              d="M6 10.5a.5.5 0 01.5-.5h3a.5.5 0 010 1h-3a.5.5 0 01-.5-.5zm-2-3a.5.5 0 01.5-.5h7a.5.5 0 010 1h-7a.5.5 0 01-.5-.5zm-2-3a.5.5 0 01.5-.5h11a.5.5 0 010 1h-11a.5.5 0 01-.5-.5z"
                              clipRule="evenodd"
                            ></path>
                          </svg>
                        </span>
                      </div>
                    </div>

                    <div className="process-vertical-content ms-lg-4">
                      <h3 className="h5">Isotope Filter</h3>
                      <p>Included Premium plugin Isotope filter & sort magical layouts.</p>
                    </div>
                  </li>
                </ol>

                {/* <!-- end processs vertical --> */}
              </div>
            </div>
          </div>

          {/* <!-- waves start --> */}
          <figure className="waves-bottom-center z-index-n1">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
              <path
                className="text-white"
                fill="currentColor"
                fillOpacity="1"
                d="M0,224L30,229.3C60,235,120,245,180,245.3C240,245,300,235,360,218.7C420,203,480,181,540,170.7C600,160,660,160,720,176C780,192,840,224,900,240C960,256,1020,256,1080,240C1140,224,1200,192,1260,186.7C1320,181,1380,203,1410,213.3L1440,224L1440,320L1410,320C1380,320,1320,320,1260,320C1200,320,1140,320,1080,320C1020,320,960,320,900,320C840,320,780,320,720,320C660,320,600,320,540,320C480,320,420,320,360,320C300,320,240,320,180,320C120,320,60,320,30,320L0,320Z"
              ></path>
            </svg>
          </figure>
        </div>
        ;{/* <!-- End Performance --> */}
        {/* <!-- =========={ PRICING }==========  --> */}
        <div id="pricing" className="section py-6 py-md-7 bg-light">
          <div className="container">
            {/* <!-- section header --> */}
            <header className="text-center mx-auto mb-5">
              <h2 className="h3 fw-bold">Our Pricing</h2>
              <hr className="divider my-4 bg-warning border-warning" />
              <p className="lead text-muted">No additional costs. Pay only one time and free for next update!</p>
            </header>

            <div className="pt-4">
              {/* <!-- row --> */}
              <div className="row justify-content-center">
                <div
                  className="col-11 col-md-6 col-lg-4 order-md-1 order-lg-1"
                  data-aos="fade-right"
                  data-aos-delay="100"
                >
                  <div className="px-lg-3">
                    {/* <!-- pricing table --> */}
                    <div className="pricing-table-one shadow-sm text-center rounded-3 mb-5 p-5">
                      {/* <!-- pricing Title --> */}
                      <div className="pricing-title my-2 my-sm-3">
                        <h3 className="h5 text-uppercase">Multisite</h3>
                      </div>
                      <div className="pricing-fee pb-2">
                        <h4 className="h2 text-primary">
                          <small>$</small>119
                        </h4>
                      </div>

                      {/* <!-- pricing content --> */}
                      <div className="pricing-content">
                        <ul className="list-unstyled">
                          <li className="py-3">Unlimited end products</li>
                          <li className="py-3">Personal or client</li>
                          <li className="py-3">Lifetime Update</li>
                          <li className="py-3">Supports 24/7</li>
                          <li className="py-3">Can&#39;t product sold</li>
                          <li className="py-3">Can&#39;t for generators</li>
                        </ul>
                      </div>

                      {/* <!-- Pricing Button --> */}
                      <div className="pricing-button py-2">
                        <Link href="https://wrapbootstrap.com/checkout?s=WB0X617B2&l=m">
                          <a target="_blank" rel="noopener" className="btn btn-secondary hover-button-up">
                            Buy Now
                          </a>
                        </Link>
                      </div>
                    </div>

                    {/* <!-- end pricing table --> */}
                  </div>
                </div>

                <div className="col-11 col-md-6 col-lg-4 order-md-3 order-lg-2" data-aos="fade-up">
                  <div className="px-lg-3">
                    {/* <!-- pricing table --> */}
                    <div className="pricing-table-one mt-lg-n4 bg-gradient-primary shadow-sm text-center rounded-3 mb-5 p-5">
                      {/* <!-- ribbon --> */}
                      <div className="ribbon ribbon-md ribbon-end">
                        <span className="bg-warning text-secondary">Popular</span>
                      </div>

                      {/* <!-- pricing title --> */}
                      <div className="pricing-title my-2 my-sm-3">
                        <h3 className="h5 text-uppercase text-white">Single</h3>
                      </div>
                      <div className="pricing-fee pb-2">
                        <h4 className="h2 text-warning">
                          <small>$</small>18
                        </h4>
                      </div>

                      {/* <!-- pricing content --> */}
                      <div className="pricing-content text-light">
                        <ul className="list-unstyled">
                          <li className="py-3">1 end products</li>
                          <li className="py-3">Personal or client</li>
                          <li className="py-3">Lifetime Update</li>
                          <li className="py-3">Supports 24/7</li>
                          <li className="py-3">Most Popular</li>
                          <li className="py-3">Can&#39;t product sold</li>
                          <li className="py-3">Can&#39;t for generators</li>
                        </ul>
                      </div>

                      {/* <!-- Pricing Button --> */}
                      <div className="pricing-button py-2">
                        <Link href="https://wrapbootstrap.com/checkout?s=WB0X617B2&l=s">
                          <a target="_blank" rel="noopener" className="btn btn-warning hover-button-up">
                            {/* <!-- <i className="fas fa-paper-plane me-2"></i> --> */}
                            🚀 Buy Now
                          </a>
                        </Link>
                      </div>
                    </div>

                    {/* <!-- end pricing table --> */}
                  </div>
                </div>

                <div
                  className="col-11 col-md-6 col-lg-4 order-md-2 order-lg-3"
                  data-aos="fade-left"
                  data-aos-delay="100"
                >
                  <div className="px-lg-3">
                    {/* <!-- pricing table --> */}
                    <div className="pricing-table-one shadow-sm text-center rounded-3 mb-5 p-5">
                      {/* <!-- pricing Title --> */}
                      <div className="pricing-title my-2 my-sm-3">
                        <h3 className="h5 text-uppercase">Extended</h3>
                      </div>
                      <div className="pricing-fee pb-2">
                        <h4 className="h2 text-primary">
                          <small>$</small>699
                        </h4>
                      </div>

                      {/* <!-- pricing content --> */}
                      <div className="pricing-content">
                        <ul className="list-unstyled">
                          <li className="py-3">1 end products</li>
                          <li className="py-3">Personal or client</li>
                          <li className="py-3">Lifetime Update</li>
                          <li className="py-3">Supports 24/7</li>
                          <li className="py-3">Can Use in product sold</li>
                          <li className="py-3">Can&#39;t for generators</li>
                        </ul>
                      </div>

                      {/* <!-- Pricing Button --> */}
                      <div className="pricing-button py-2">
                        <Link href="https://wrapbootstrap.com/checkout?s=WB0X617B2&l=e">
                          <a target="_blank" rel="noopener" className="btn btn-secondary hover-button-up">
                            Buy Now
                          </a>
                        </Link>
                      </div>
                    </div>

                    {/* <!-- end pricing table --> */}
                  </div>
                </div>

                <div className="col-12 order-4">
                  <p className="text-center font-small text-muted mb-0">
                    <Link href="#">
                      <a className="text-muted" rel="noopener" target="_blank">
                        {/* <!-- <i className="fas fa-balance-scale me-1"></i>  --> */}
                        🚀 Full license details
                      </a>
                    </Link>
                  </p>
                </div>
              </div>

              {/* <!-- end row --> */}
            </div>
          </div>
        </div>
        {/* <!-- End Pricing --> */}
      </main>
    </>
  );
};

export default Home;
