import { InferGetServerSidePropsType, NextPage } from 'next';
import Head from 'next/head';

export async function getServerSideProps() {
  return {
    props: {},
  };
}

const Home = ({}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main id="content"></main>
    </>
  );
};

export default Home;
